# Projeto de Data Science: Previsão de Vencedores em eSports de League of Legends

# Introdução

O objetivo principal deste projeto é desenvolver um modelo preditivo capaz de prever o resultado de uma partida de League of Legends com base em informações disponíveis antes do início do jogo. Isso pode ser útil para jogadores, equipes profissionais, casas de apostas e analistas que desejam ter uma visão preditiva do desempenho das equipes.

A base de dados utilizada se encontra em: https://gol.gg/

In [1]:
import pandas as pd
import sweetviz as sv

In [2]:
df = pd.read_excel('meu_dataframe.xlsx')

In [3]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,53,54,55,56,57,58,59,60,61,62
0,Time,Drake,Baron,Resultado,Player,Champion,NaN,Role,Level,Kills,...,Total Damage Shielded On Teammates,Time ccing others,Total Time CC Dealt,Total damage taken,Total Time Spent Dead,Consumables purchased,Items Purchased,Shutdown bounty collected,Shutdown bounty lost,['56817']
1,paiN Gaming,1,1,LOSS,Wizer,Aatrox,NaN,TOP,18,9,...,0,26,312,45929,155,11,30,1450,900,['56817']
2,paiN Gaming,1,1,LOSS,Cariok,Rell,NaN,JUNGLE,17,0,...,0,39,1037,30110,230,17,33,0,0,['56817']
3,paiN Gaming,1,1,LOSS,dyNquedo,Ahri,NaN,MID,18,7,...,0,27,98,23208,238,22,43,350,650,['56817']
4,paiN Gaming,1,1,LOSS,Titan,Kalista,NaN,ADC,18,6,...,0,25,517,24370,195,10,34,150,400,['56817']

In [4]:
#Engenharia de dados com as informações coletadas
df = pd.read_excel('meu_dataframe.xlsx')
df_drake = df.loc[df[1] == 'Drake'].iloc[[0]]
df = df.loc[df[1] != 'Drake']
df = pd.concat([df_drake,df])
df.columns = df.iloc[0]
df = df.drop(0)
df = df.drop('Role', axis=1)
df = df.drop('Player', axis=1)
df = df.drop('Champion', axis=1)
df = df.drop('GOLD%', axis=1)
df = df.drop('VS%', axis=1)
df = df.drop('DMG%', axis=1)
df = df.drop('KP%', axis=1)
df = df.drop('Solo kills', axis=1)
df = df.drop('Double kills', axis=1)
df = df.drop('Triple kills', axis=1)
df = df.drop('Quadra kills', axis=1)
df = df.drop('Penta kills', axis=1)
df.dropna(axis=1, how='all')
pd.set_option('display.max_columns', None)
df.fillna(0, inplace=True)
df['Resultado'] = df['Resultado'].replace({'WIN': 1, 'LOSS': 0})
df['KDA'] = df['KDA'].replace({'Perfect KDA': 8})
for coluna in df.columns:
    df[coluna] = pd.to_numeric(df[coluna], errors='ignore')
df = df.groupby(['Time', "['56817']",'Resultado']).sum().reset_index()
df = df.drop("['56817']", axis=1)
df = df.dropna(axis=1)

In [5]:
df.describe()

,Resultado,Drake,Baron,NaN,Level,Kills,Deaths,Assists,KDA,CS,CS in Team's Jungle,CS in Enemy Jungle,CSM,Golds,GPM,Vision Score,Wards placed,Wards destroyed,Control Wards Purchased,Detector Wards Placed,VSPM,WPM,VWPM,WCPM,Total damage to Champion,Physical Damage,Magic Damage,True Damage,DPM,K+A Per Minute,GD@15,CSD@15,XPD@15,LVLD@15,Objectives Stolen,Damage dealt to turrets,Damage dealt to buildings,Total heal,Total Heals On Teammates,Damage self mitigated,Total Damage Shielded On Teammates,Time ccing others,Total Time CC Dealt,Total damage taken,Total Time Spent Dead,Consumables purchased,Items Purchased,Shutdown bounty collected,Shutdown bounty lost
count,180.000000,180.000000,180.000000,180.0,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.0,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.00000,180.000000,180.00000,180.00000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000,180.000000
mean,0.500000,12.500000,4.055556,0.0,75.916667,13.544444,13.600000,33.955556,24.621111,1088.794444,196.372222,0.0,32.315556,60946.950000,1802.300000,300.461111,124.900000,58.116667,45.694444,42.144444,8.782944,3.658722,1.342722,1.692389,76291.972222,35511.494444,36566.966667,4213.511111,2216.705556,1.402389,0.000000,0.000000,0.000000,0.00000,0.155556,15850.70000,15850.70000,38111.172222,3419.255556,117493.138889,3593.600000,127.694444,2874.127778,105174.422222,395.872222,56.277778,143.466667,612.500000,613.333333
std,0.501395,7.758578,4.221152,0.0,7.466031,7.117782,7.121139,19.613535,17.222439,179.508662,41.185780,0.0,2.115857,12115.711842,177.097104,81.574271,33.857424,19.426491,12.308918,12.146279,1.140710,0.538597,0.224208,0.375231,27140.478502,14571.691669,14710.533115,3267.010747,514.581651,0.772586,2064.260829,28.725633,1508.440087,1.44933,0.406954,8520.12326,8520.12326,14950.849290,4122.551363,50719.846526,4826.075138,60.508469,2549.886620,30817.540552,238.850437,14.024741,22.954023,567.038642,568.311230
min,0.000000,0.000000,0.000000,0.0,59.000000,0.000000,0.000000,0.000000,0.000000,734.000000,117.000000,0.0,26.500000,40506.000000,1475.000000,164.000000,73.000000,26.000000,21.000000,21.000000,6.170000,2.620000,0.700000,0.930000,32633.000000,12220.000000,12839.000000,377.000000,1005.000000,0.000000,-5066.000000,-97.000000,-3804.000000,-4.00000,0.000000,0.00000,0.00000,12081.000000,0.000000,46929.000000,0.000000,37.000000,515.000000,53891.000000,0.000000,30.000000,101.000000,0.000000,0.000000
25%,0.000000,5.000000,0.000000,0.0,69.750000,8.000000,8.000000,18.000000,9.350000,952.500000,167.000000,0.0,31.000000,51238.250000,1640.000000,239.000000,101.000000,45.000000,37.000000,33.000000,8.025000,3.247500,1.207500,1.450000,56472.500000,24337.000000,26018.250000,1860.750000,1874.750000,0.787500,-1349.000000,-20.000000,-1100.000000,-1.00000,0.000000,8093.75000,8093.75000,28607.750000,734.250000,82016.250000,968.500000,92.250000,1507.500000,83111.000000,213.000000,46.000000,126.000000,187.500000,187.500000
50%,0.500000,15.000000,5.000000,0.0,76.000000,14.000000,14.000000,34.000000,21.850000,1051.000000,192.000000,0.0,32.250000,59349.500000,1798.000000,290.000000,119.000000,56.000000,44.000000,41.000000,8.825000,3.565000,1.345000,1.670000,67952.000000,31843.000000,32793.000000,3099.500000,2151.500000,1.380000,0.000000,0.000000,0.000000,0.00000,0.000000,16307.00000,16307.00000,35163.000000,1725.000000,100071.000000,2290.000000,119.500000,2247.000000,95715.500000,362.000000,55.000000,139.000000,450.000000,450.000000
75%,1.000000,20.000000,5.000000,0.0,82.250000,18.000000,18.000000,47.000000,37.500000,1219.000000,222.000000,0.0,33.625000,68946.000000,1938.000000,344.250000,142.250000,70.250000,54.250000,49.250000,9.492500,4.020000,1.500000,1.880000,92121.500000,44445.250000,45937.500000,5787.000000,2543.250000,1.837500,1349.000000,20.000000,1100.000000,1.00000,0.000000,23949.50000,23949.50000,46151.500000,4011.250000,141567.000000,4822.000000,144.250000,3273.000000,122925.250000,572.000000,65.000000,160.250000,862.500000,862.500000
max,1.000000,30.000000,20.000000,0.0,90.000000,34.000000,34.000000,92.000000,75.300000,1631.000000,361.000000,0.0,38.100000,94148.000000,2243.000000,571.000000,216.000000,115.000000,78.000000,76.000000,12.410000,5.040000,1.890000,2.850000,157732.000000,78298.000000,93118.000000,18549.000000,3644.000000,4.120000,5066.000000,97.000000,3804.000000,4.00000,2.000000,30823.00000,30823.00000,92825.000000,21716.000000,301746.000000,50830.000000,467.000000,19498.000000,202850.000000,1156.000000,93.000000,206.000000,2350.000000,2350.000000

In [6]:
df.describe().columns

Index([                         'Resultado',
                                    'Drake',
                                    'Baron',
                                        nan,
                                    'Level',
                                    'Kills',
                                   'Deaths',
                                  'Assists',
                                      'KDA',
                                       'CS',
                      'CS in Team's Jungle',
                       'CS in Enemy Jungle',
                                      'CSM',
                                    'Golds',
                                      'GPM',
                             'Vision Score',
                             'Wards placed',
                          'Wards destroyed',
                  'Control Wards Purchased',
                    'Detector Wards Placed',
                                     'VSPM',
                                      'WPM',
                                     'VWPM',
                                     'WCPM',
                 'Total damage to Champion',
                          'Physical Damage',
                             'Magic Damage',
                              'True Damage',
                                      'DPM',
                           'K+A Per Minute',
                                    'GD@15',
                                   'CSD@15',
                                   'XPD@15',
                                  'LVLD@15',
                        'Objectives Stolen',
                  'Damage dealt to turrets',
                'Damage dealt to buildings',
                               'Total heal',
                 'Total Heals On Teammates',
                    'Damage self mitigated',
       'Total Damage Shielded On Teammates',
                        'Time ccing others',
                      'Total Time CC Dealt',
                       'Total damage taken',
                    'Total Time Spent Dead',
                    'Consumables purchased',
                          'Items Purchased',
                'Shutdown bounty collected',
                     'Shutdown bounty lost'],
      dtype='object', name=0)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180 entries, 0 to 179
Data columns (total 50 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Time                                180 non-null    object
 1   Resultado                           180 non-null    int64
 2   Drake                               180 non-null    int64
 3   Baron                               180 non-null    int64
 4   nan                                 180 non-null    float64
 5   Level                               180 non-null    int64
 6   Kills                               180 non-null    int64
 7   Deaths                              180 non-null    int64
 8   Assists                             180 non-null    int64
 9   KDA                                 180 non-null    float64
 10  CS                                  180 non-null    int64
 11  CS in Team's Jungle                 180 non-null    int64
 12  CS in Enemy Jungle                  180 non-null    int64
 13  CSM                                 180 non-null    float64
 14  Golds                               180 non-null    int64
 15  GPM                                 180 non-null    int64
 16  Vision Score                        180 non-null    int64
 17  Wards placed                        180 non-null    int64
 18  Wards destroyed                     180 non-null    int64
 19  Control Wards Purchased             180 non-null    int64
 20  Detector Wards Placed               180 non-null    int64
 21  VSPM                                180 non-null    float64
 22  WPM                                 180 non-null    float64
 23  VWPM                                180 non-null    float64
 24  WCPM                                180 non-null    float64
 25  Total damage to Champion            180 non-null    int64
 26  Physical Damage                     180 non-null    int64
 27  Magic Damage                        180 non-null    int64
 28  True Damage                         180 non-null    int64
 29  DPM                                 180 non-null    int64
 30  K+A Per Minute                      180 non-null    float64
 31  GD@15                               180 non-null    int64
 32  CSD@15                              180 non-null    int64
 33  XPD@15                              180 non-null    int64
 34  LVLD@15                             180 non-null    int64
 35  Objectives Stolen                   180 non-null    int64
 36  Damage dealt to turrets             180 non-null    int64
 37  Damage dealt to buildings           180 non-null    int64
 38  Total heal                          180 non-null    int64
 39  Total Heals On Teammates            180 non-null    int64
 40  Damage self mitigated               180 non-null    int64
 41  Total Damage Shielded On Teammates  180 non-null    int64
 42  Time ccing others                   180 non-null    int64
 43  Total Time CC Dealt                 180 non-null    int64
 44  Total damage taken                  180 non-null    int64
 45  Total Time Spent Dead               180 non-null    int64
 46  Consumables purchased               180 non-null    int64
 47  Items Purchased                     180 non-null    int64
 48  Shutdown bounty collected           180 non-null    int64
 49  Shutdown bounty lost                180 non-null    int64
dtypes: float64(8), int64(41), object(1)
memory usage: 70.4+ KB

In [8]:
report = sv.analyze(df)

# Exibir o relatório no navegador padrão
report.show_html('sweetviz2_report.html')

                                             |          | [  0%]   00:00 -> (? left)

Report sweetviz2_report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.

In [9]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import make_pipeline




X = df.drop(columns=['Resultado'])
X.columns = X.columns.astype(str)

X = pd.get_dummies(X)  # Se houver variáveis categóricas
y = df['Resultado']

# Dividir os dados em conjunto de treinamento e conjunto de teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=5)

# Inicializar os modelos de classificação
models = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree": DecisionTreeClassifier(random_state=5),
    "Random Forest": RandomForestClassifier(n_estimators=100, random_state=5),
    "Gradient Boosting": GradientBoostingClassifier(n_estimators=100, random_state=5),
    "Neural Network": make_pipeline(StandardScaler(), MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=500, random_state=5))
}

# Treinar e avaliar cada modelo
results = {}
for name, model in models.items():
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)
    accuracy = accuracy_score(y_test, predictions)
    classification_rep = classification_report(y_test, predictions)
    conf_matrix = confusion_matrix(y_test, predictions)
    results[name] = {"accuracy": accuracy, "classification_report": classification_rep, "confusion_matrix": conf_matrix}

# Imprimir resultados
for name, result in results.items():
    print(f"{name}:")
    print("Accuracy:", result['accuracy'])
    print("Classification Report:\n", result['classification_report'])
    #print("Confusion Matrix:\n", result['confusion_matrix'])

c:\Users\Rebor\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

Logistic Regression:
Accuracy: 0.6111111111111112
Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.55      0.63        22
           1       0.50      0.71      0.59        14

    accuracy                           0.61        36
   macro avg       0.62      0.63      0.61        36
weighted avg       0.65      0.61      0.61        36

Decision Tree:
Accuracy: 0.5833333333333334
Classification Report:
               precision    recall  f1-score   support

           0       0.68      0.59      0.63        22
           1       0.47      0.57      0.52        14

    accuracy                           0.58        36
   macro avg       0.58      0.58      0.58        36
weighted avg       0.60      0.58      0.59        36

Random Forest:
Accuracy: 0.6666666666666666
Classification Report:
               precision    recall  f1-score   support

           0       0.75      0.68      0.71        22
           1       0.56      0.64      0.60        14

    accuracy                           0.67        36
   macro avg       0.66      0.66      0.66        36
weighted avg       0.68      0.67      0.67        36

Gradient Boosting:
Accuracy: 0.5833333333333334
Classification Report:
               precision    recall  f1-score   support

           0       0.68      0.59      0.63        22
           1       0.47      0.57      0.52        14

    accuracy                           0.58        36
   macro avg       0.58      0.58      0.58        36
weighted avg       0.60      0.58      0.59        36

Neural Network:
Accuracy: 0.5833333333333334
Classification Report:
               precision    recall  f1-score   support

           0       0.68      0.59      0.63        22
           1       0.47      0.57      0.52        14

    accuracy                           0.58        36
   macro avg       0.58      0.58      0.58        36
weighted avg       0.60      0.58      0.59        36

Projeto ainda em desenvolvimento